version: '3'

services:
  app_test:
    container_name: clerk_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app/
    depends_on:
      - clerk-postgres
    networks:
      - clerk_test

  clerk-postgres:
    image: postgres:latest
    container_name: clerk_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - clerk_test
  
  
volumes:
  api_test:
  database_postgres:

networks:
  clerk_test:
    driver: bridge